### PR TITLE
shouldn’t throw exception in __toString magic method

### PR DESCRIPTION
**Pull request by basz**
https://devzone.zend.com/930/zend-weekly-summaries-issue-336/#Heading6

### CODE REVIEW

**Comment by basz** [comment]
I don't want to to do that as it would BC. but for next version yes

**Comment by svycka** [comment]
ok agreed, but then maybe don't change this in this version

**Comment by basz** [comment]
exceptions in __toString can not work, they fatally error. so it is ok to simply return a ''. I don't think anyone has ever hit this, but still

**Comment by svycka** [comment]
ok

**Pull request merged**
