### PR TITLE
Service manager v3 and event manager v3 support

### PR DESCRIPTION
**Pull request by svycka**
this should not have BC break but well if someone (not me) could test this would be great.(works on my project but I don't use all the features)

unfortenetly we can't have zend-mvc 3.0 in BC free way so better do another PR and release new major version.

any comments @juriansluiman ?

### CODE REVIEW

**Comment by svycka** [comment]
@basz maybe you can merge?

**Comment by basz** [comment]
@svycka sorry I don't have write access here

**Comment by svycka** [comment]
@basz ok,  maybe you know where @juriansluiman gone?

**Comment by basz** [comment]
Nope. He moved away from development and haven't heard since from him, i'v tried several times to contact him.  no luck.. :/ You could try his twitter handler...

**Comment by svycka** [comment]
I guess its no matter if he moved away from development will have to fork I guess

**Comment by basz** [comment]
i ave reached out to him, lets wait a day or so... otherwise I would say go ahead and fork

**Comment by svycka** [comment]
ok thanks

**Comment by basz** [comment]
@svycka I now have write access. The repo moved to my namespace but composer should still work with the same package name... I'll have a look a. bit later to what you changed and merge if everything is ok... so progress... :-)

I think the tests now ran also

Would you be willing to maintain this package together? I don't use it anymore in new projects so it won't receive to much love from me :-/

**Comment by svycka** [comment]
@basz I still use, but not that much as before. But if you want I can try to help maintaining it as I still use it on few projects.

**Pull request merged**
