### PR TITLE
dependency update

### PR DESCRIPTION
**Pull request by kokspflanze**
added php80 in composer and travis
removed deprecated laminas-console

about travis looks like is dead, maybe it should be changed to the github workflow.

### CODE REVIEW

**Comment by kokspflanze** [comment]
@svycka is there any way for a php8 and php81 support?

**Comment by svycka** [comment]
@kokspflanze maybe you could rebase? :) and also change the branch from master to develop?

**Comment by kokspflanze** [comment]
@svycka i will do that in the evening, hope that is fine=)

**Comment by demiankatz** [comment]
@kokspflanze, after rebasing, please uncomment these lines in the GitHub Actions workflow, and then we can make sure tests pass on PHP 8.0 and 8.1:

https://github.com/basz/SlmLocale/blob/master/.github/workflows/ci.yaml#L18-L29

Thanks to you and @svycka for moving this forward; looking forward to reaching 1.0.0 at last! :-)

**Comment by kokspflanze** [comment]
@demiankatz you see any reason why vendor/bin/php-coveralls fails?

**Comment by demiankatz** [comment]
@kokspflanze, I'm not familiar with the Coveralls tool, so I don't have specific advice to offer based on domain knowledge. However, I wonder if we should turn off the coverage option for PHP 7.4 and turn it on for a newer PHP version. If the problem is based on using old PHP, that would fix it. It was always my intention to run coverage on the newest PHP rather than the oldest, but I put it on for PHP 7.4 initially because we had to disable 8.x until this PR is done.

I'll do a little more investigation and let you know if I turn up any other ideas.

**Comment by demiankatz** [comment]
@kokspflanze, I ran Coveralls with the `--verbose` flag in my local environment and got this:

```
Coverage:  69.76% (316/453)
Collect git info
Read environment variables
Requirements are not satisfied.

Set environment variables properly like the following.

[...]

For Github Actions users:
  - GITHUB_REF
  - GITHUB_ACTIONS
  - GITHUB_RUN_ID
  - GITHUB_EVENT_NAME
  - COVERALLS_REPO_TOKEN

elapsed time: 0.059 sec memory: 6.00 MB
```

My guess is that we need to set the COVERALLS_REPO_TOKEN somehow. I'm not sure where that value comes from; it was not explicitly included in the old Travis configuration, so I'm not sure how it was injected previously -- maybe it was a setting on the Travis side. Maybe @svycka can shed some light on this.

**Comment by demiankatz** [comment]
(Perhaps the most sensible thing to do is to turn off coverage in the whole matrix for now, and deal with this problem separately -- it looks like Coveralls data hasn't been exporting successfully since 2020 anyway, so it's not a new problem).

**Comment by kokspflanze** [comment]
@demiankatz i disabled the coverage

**Comment by demiankatz** [comment]
I'll wait for @svycka's input before taking further action, but if it would be helpful for me to write up an issue to track the Coveralls situation, I'm happy to do so.

**Comment by svycka** [comment]
I think we will need environments permission, but I don't have and also don't have access to coveralls. I guess we can hope @basz can help us with this.
But it is not a critical issue so I will merge it as it is.

**Pull request merged**
