### PR TITLE
Fixing #26 - broken unit tests

### PR DESCRIPTION
**Pull request by koseduhemak**
Fixing #26 - broken unit tests.

### CODE REVIEW

**Comment by koseduhemak** [comment]
travis is failing because of invalid (?) composer configuration. I did not change anything within composer.json, so it has to be in there before my pull request... Any ideas?

**Comment by basz** [comment]
not sure, but we recently added a development branch. could you and change the target branch to develop?

**Comment by koseduhemak** [comment]
ok changed target branch to `develop`. Is it possible to rerun travis?

**Comment by basz** [comment]
apparently not without a push. it's redoing the same branch...

**Comment by koseduhemak** [comment]
ok then it is maybe easier to close this pull request and I initiate another one in the correct branch.

**Comment by svycka** [comment]
master and develop should be equal at the moment that's more like composer problem.

also, @koseduhemak when you create PR create it not from master because we can't edit or fix problems on your master branch instead create feature or hotfix branch and create PR from it

**Comment by koseduhemak** [comment]
ok then we can maybe close this pr and I open a new one with source branch `feature-phpunit` to target branch `develop`.

**Comment by koseduhemak** [comment]
closing here. See #99

**Pull request closed without merging**
