### PR TITLE
Patch php83

### PR DESCRIPTION
**Pull request by kokspflanze**

### CODE REVIEW

**Comment by svycka** [comment]
nice, it almost passed :D

**Comment by kokspflanze** [comment]
@svycka should i fix the parts? or a new pr for that?

**Comment by svycka** [comment]
do not matter to me where, but it would be nice to have it green before merging

**Comment by kokspflanze** [comment]
@svycka i fixed the cs parts, now its green=)

**Comment by svycka** [comment]
thanks @kokspflanze

**Pull request merged**
