### PR TITLE
fix #26 - feature/phpunit

### LINKED ISSUE #26: Unit testing applications using SlmLocale
I'm attempting to create unit tests for my application which makes use of SlmLocale UriPathStrategy and am having issues with testing controller dispatches like so:

``` php
public function testLoginActionCanBeAccessed()
{
    $this->dispatch('/en/account/login');
    $this->assertResponseStatusCode(200);
}
```

This returns 302 and when I dump the RequestURI within UriPathStrategy, I'm getting the following twice:

``` php
class Zend\Uri\Http#819 (10) {
  protected $validHostTypes => int(19)
  protected $user => NULL
  protected $password => NULL
  protected $scheme => string(4) "http"
  protected $userInfo =>  NULL
  protected $host => NULL
  protected $port => NULL
  protected $path => string(1) "/"
  protected $query => NULL
  protected $fragment => NULL
}
```

Whereas when I dump the RequestURI from a typical request via my browser:

``` php
object(Zend\Uri\Http)[210]
  protected 'validHostTypes' => int 19
  protected 'user' => null
  protected 'password' => null
  protected 'scheme' => string 'http' (length=4)
  protected 'userInfo' => null
  protected 'host' => string 'konoro.dev' (length=16)
  protected 'port' => null
  protected 'path' => string '/en/' (length=4)
  protected 'query' => string '' (length=0)
  protected 'fragment' => null
```

From what I've been reading in the code, it looks like the only time detection is done (and redirection) is onBootstrap of the Module. So the unit test defaults to / without a locale and every other dispatch uses the same requestUri and it needs to redirect to /en/ with them all.

Are you doing anything in particular when testing your stuff or does there need to be some change so the detection is done onDispatch() instead?

Thanks, Dom

### PR DESCRIPTION
**Pull request by koseduhemak**
Fixing issue #26.

### CODE REVIEW

**Comment by koseduhemak** [comment]
fixed travis by bumping version of "zendframework/zend-modulemanager" depedency to "^2.8.2".
Please have a look if we can now merge.

**Comment by koseduhemak** [comment]
any news regarding this pull request?

**Comment by basz** [comment]
missed this one. seems reasonable i guess...

**Comment by koseduhemak** [comment]
Thank you for merging, when will it available in master, to let me / people pull it from composer?

**Comment by basz** [comment]
not sure, @svycka?

however for now you could point to the developer branch in composer until it is released i think

```
"require": {
        "slm/locale": "dev-developer"
    }
```

**Comment by svycka** [comment]
I don't like this workaround but also don't have much time to fix this issue so we can create release

**Comment by koseduhemak** [comment]
I agree with you, @svycka . Problem is though that there is no easy fix, because of the short-circuit of the event processing while creating the application (getApplication()). However, with this fix the phpunit tests working again, so one can use this module in combination with custom phpunit tests (extending AbstractControllerTestCase) only that way at the moment. Otherwise all such tests will fail and break testability.

**Comment by svycka** [comment]
maybe it was possible to add strategy for tests with higher priority to prevent other strategies like uripath? Okay just guessing but I hope there is a better way to do this.

The biggest problem here is that when we remove this workaround this will be BC break not a good thing for workaround :D

But again I don't have time at the moment so if this is a problem then we can do it like this if we don't have other options.

**Comment by koseduhemak** [comment]
@svycka: Ok I will try to add a custom strategy which does the fix... I would propose that I create another pr if I finished and we leave this one as it is (if the strategy approach is not working). We can revert before merge of this pr, if strategy approach works :D

What do you think, is this a good way to go?

**Comment by svycka** [comment]
I guess it would be better as it would not require any code in this library this could only be added to documentation only

**Comment by koseduhemak** [comment]
Please have a look at #100

**Pull request merged**
